### ISSUE TITLE
i can  do it .for custom Launcher 

### ISSUE THREAD

**Issue by chongbo2013** [AndroidDeveloperLB/LB-Launcher#1]
We customize his if he supports 4.1 +

**Comment by AndroidDeveloperLB** [comment]
You can do what exactly? 
Also, this project does support Android 4.1 . In fact, that's the minimal version:

```
defaultConfig {
        applicationId "com.lb.launcher"
        minSdkVersion 16
```

API 16 is Android 4.1 :
http://developer.android.com/about/versions/android-4.1.html

**Comment by chongbo2013** [comment]
is can run on 4.1 ?

**Comment by chongbo2013** [comment]
i can do custom  Launcher.  like  Apus Launcher  or  Hola Launcher . base your LB-Launcher . if can supput 4.1+

**Comment by AndroidDeveloperLB** [comment]
I'd prefer you try to contribute here too, since this is intended to be an open sourced launcher, as opposed to the others. 
And as I've already written, it supports 4.1 version of Android.
