### ISSUE TITLE
Google search bar

### ISSUE THREAD

**Issue by vashdstampede** [AndroidDeveloperLB/LB-Launcher#2]
Hi,

Downloaded the launcher and seems to be working properly except there's is no google search bar and can't set default analog clock widget. How can I included it in the launcher? 

Thanks

**Comment by AndroidDeveloperLB** [comment]
I'm pretty sure that what I got is from the clean code, meaning nothing from any company.
If you wish to add something, you need to understand the code and add it by yourself. Sadly most of the things I did here is to import the code,without fully understand what's going on and so I don't know how to add features to it easily.
I was hoping that by making this project, people would take it and make some other great (hopefully even open sourced ) launchers.
