### ISSUE TITLE
Changing package name & signing the app.

### ISSUE THREAD

**Issue by webbisswiftapps** [AndroidDeveloperLB/LB-Launcher#4]
Hi,

Thanks to your work, I have been developing an "accessibility" launcher based on LB Launcher.
I wanted to change the package name but when I did, I went through a lot of issues. Are there any steps that I need to follow to change the package name?

Also, I would like to release this app at some point and I cannot create release apks as of now. Can you help me with that?

**Comment by AndroidDeveloperLB** [comment]
As I remember, this also took a lot of time for me to change the package name. I suggest doing it very carefully, and start by searching globally for the package name I used.

As for releasing apk files, if you fail to do it, you should report about this as a bug on the issue tracker:

https://issuetracker.google.com/issues

Good luck!

**Comment by webbisswiftapps** [comment]
Thanks for your reply!
